name: Encrypt Page

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  encrypt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install staticrypt
        run: sudo npm install -g staticrypt
      - name: Remove template salt (if necessary)
        run: |
          current_salt="$(grep -oP '(?<="salt": ")[^"]*' .staticrypt.json)"
          if [ "${{ github.repository }}" != "a-nau/password-protected-website-template" ] && [ "$current_salt" == "9fdd6a30e734b0ce7de31a0a221786bf" ];
          then
            rm .staticrypt.json
          fi
      # - name: Embed assets
      #   run: |
      #     pip3 install beautifulsoup4
      #     python3 embed.py
      - name: Encrypt index
        run: staticrypt main.html ${{ secrets.DECRYPTION_PASSPHRASE }} -f password_template.html -o index.html --title "Login" --instructions "This is a test website, use the password 'test' to enter." --decrypt-button "Open Page" --embed true
        # run: staticrypt index.html ${{ secrets.DECRYPTION_PASSPHRASE }} -f password_template.html -o index.html --title "Login" --instructions "This is a test website, use the password 'test' to enter." --decrypt-button "Open Page" --embed true
      - name: Commit files
        run: |
          git config --local user.name "Github Action"
          git add .
          git commit -m "encrypted files"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
